### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by jo-lyn** [cs3217-dash/dash#13]
# Jolyn
- [x] Mission for coins
- [x] Divide distance by 10
- [x] Gameover scene after highscore
- [x] Icons in menu
- [x] Back buttons
- [x] Coins collected in game scene (coins might be double counting)
- [x] Ghost mode selection instead of after replay
- [x] Input validation + error feedback
- [x] Check if player is in leaderboard (need help for this tmr)

# Yee Chin
- [x] Pause-able shadow
- [x] Multiplayer of Shrink and Ghost state
- [x] Highscore from menu & loading
- [x] Seeding for game
- [ ] Multiplayer of Dash (TBC)
- [x] Countdown at the start

# Jie Liang
- [x] Assets for obstacles (normal and moving), three power ups and coins, different sprite
- [x] power up state/animation
- [x] glowing
- [x] more parallax particles
- [x] particles stick to scene not node
- [x] poster
- [ ] video

# Tomorrow
- [ ] Sound effects
- [ ] BG Music
